Possible fix for SFSDK-60
citrix/ShareFile-PowerShell pull request #37
Opened 2017-09-25 04:47 UTC by vkvikaskmr

The file UploadAction class, while uploading the file creates a reference and points to FileInfo object. This object stays in the heap even after the CopyFileItem method of class UploadAction goes out of scope. We cannot call dispose() method on FileInfo object as it does not implement IDispose interface. Hence we are calling Garbage Collector explicitly.

2017-09-26 15:59 UTC, rgmills commented on ShareFileSnapIn/SyncSfItem.cs
> +                GC.Collect();
Will this actually solve the problem?  Or is there a more fundamental issue with how the SDK is supporting parallel operations?

2017-09-27 11:53 UTC, vkvikaskmr commented on ShareFileSnapIn/SyncSfItem.cs
> +                GC.Collect();
I looked deeper into the code. Looks like the root cause is different. I will look further and update my findings here.

2017-09-27 13:05 UTC, rgmills requested changes
Hold for updates from @vkvikaskmr

2017-09-28 11:28 UTC, vkvikaskmr commented on ShareFileSnapIn/SyncSfItem.cs
> +                GC.Collect();
Couldn't figure out the root cause. Here are few observations.

- No issue with the completion of upload and starting of deletion logic. Verified this by putting a suitable wait after upload completes. This did not fix the problem.

- I bypassed the parallel operations logic and performed upload right in the SyncSFItem.cs file. This too did not fix the problem.
From these observations I felt that the issue is with uploaders object that we get from ShareFile.api.client library but when I looked into their code, there doesn't seem to be any problem. They are performing cleanups whenever possible.

2026-06-12 16:14 UTC, closed without merging